package liittyma;

import java.text.DecimalFormat;
import javax.swing.DefaultComboBoxModel;
import logiikka.Osake;
import logiikka.Toimiala;

/**
 *
 * Luokka tarjoaa käyttäjälle käyttöliittymän valitun osakkeen tietojen 
 * muuttamiseen. Käyttöliittymä ei kuitenkaan mahdollista osakekauppaa:
 * ainoastaan osakkeen tietojen päivittäminen on mahdollista.
 *
 * @author gexgex
 */
public class MuutaTietojaGUI extends javax.swing.JFrame {

    /**
     * Creates new form MuutaTietojaGUI
     */
    public MuutaTietojaGUI() {
        initComponents();
    }

    public MuutaTietojaGUI(OsakesalkkuGUI aThis) {
        vanhempi = aThis;
        df2 = new DecimalFormat("0.00");
        initComponents();
        toimialaComboBox.setModel(new DefaultComboBoxModel(Toimiala.values()));
        osake = vanhempi.getOsake();
        toimialaComboBox.setSelectedItem(osake.getToimiala());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nimiLabel = new javax.swing.JLabel();
        nimiTextField = new javax.swing.JTextField();
        hintaTextField = new javax.swing.JTextField();
        toimialaComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        betaTextField = new javax.swing.JTextField();
        volaTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        muutaButton = new javax.swing.JButton();
        nykNimiLabel = new javax.swing.JLabel();
        nykArvoLabel = new javax.swing.JLabel();
        nykAlaLabel = new javax.swing.JLabel();
        nykBetaLabel = new javax.swing.JLabel();
        nykVolaLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        paluuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Muuta osakeen tietoja");

        nimiLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        nimiLabel.setText("Osakkeen nimi");

        toimialaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        toimialaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toimialaComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Riski");

        betaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betaTextFieldActionPerformed(evt);
            }
        });

        volaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volaTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Uusi nimi:");

        jLabel3.setText("Uusi arvo:");

        jLabel4.setText("Uusi toimiala:");

        jLabel5.setText("Uusi beta:");

        jLabel6.setText("Uusi volatiliteetti:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Perustiedot");

        muutaButton.setText("Muuta");
        muutaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muutaButtonActionPerformed(evt);
            }
        });

        nykNimiLabel.setText("-");

        nykArvoLabel.setText("-");

        nykAlaLabel.setText("-");

        nykBetaLabel.setText("-");

        nykVolaLabel.setText("-");

        jLabel8.setText("Nykyinen nimi");

        jLabel9.setText("Nykyinen arvo");

        jLabel10.setText("Nykyinen toimiala");

        jLabel11.setText("Nykyinen beta");

        jLabel12.setText("Nykyinen volatiliteetti");

        paluuButton.setText("Paluu");
        paluuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paluuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nykAlaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(toimialaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(hintaTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                        .addComponent(nimiTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(nykArvoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nykNimiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(paluuButton)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(volaTextField)
                                        .addComponent(betaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(muutaButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nykVolaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(nykBetaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(nimiLabel))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nimiLabel)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(nykNimiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(nykArvoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nykAlaLabel)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(nykBetaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(nykVolaLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(betaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(volaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(muutaButton)
                            .addComponent(paluuButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nimiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hintaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toimialaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toimialaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toimialaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toimialaComboBoxActionPerformed

    private void volaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volaTextFieldActionPerformed

    private void muutaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muutaButtonActionPerformed
        // TODO add your handling code here:
        String nimi = nimiTextField.getText();
        String arvoTxt = hintaTextField.getText();
        String betaTxt = betaTextField.getText();
        String volaTxt = volaTextField.getText();

        if (!onNumeerinenJaPositiivinen(arvoTxt) || arvoTxt.isEmpty()) {
            if (!arvoTxt.isEmpty()) {
                tietoVaarassaMuodossa();
                return;
            }
        } else {
            osake.setHinta(Double.parseDouble(arvoTxt));
        }

        if (!onNumeerinenJaPositiivinen(betaTxt) || betaTxt.isEmpty()) {
            if (!betaTxt.isEmpty()) {
                tietoVaarassaMuodossa();
                return;
            }
        } else {
            osake.getRiski().setBeta(Double.parseDouble(betaTxt));
        }

        if (!onNumeerinenJaPositiivinen(volaTxt) || volaTxt.isEmpty()) {
            if (!volaTxt.isEmpty()) {
                tietoVaarassaMuodossa();
                return;
            }
        } else {
            osake.getRiski().setVolatiliteetti(Double.parseDouble(volaTxt));
        }

        if (!nimi.isEmpty()) {
            osake.setNimi(nimi);
        }

        osake.setToimiala((Toimiala) toimialaComboBox.getSelectedItem());

        vanhempi.paivitaLista();

        super.dispose();
    }//GEN-LAST:event_muutaButtonActionPerformed

    private void betaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_betaTextFieldActionPerformed

    private void paluuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paluuButtonActionPerformed
        super.dispose();
    }//GEN-LAST:event_paluuButtonActionPerformed

    /**
     * Metodi asettaa osakkeen tiedot käyttäjän nähtäville.
     */
    public void asetaTiedot() {
        nimiLabel.setText("Muuta osakkeen " + osake.getNimi() + " tietoja");
        nykNimiLabel.setText(osake.getNimi());
        nykArvoLabel.setText(df2.format(osake.getHinta()) + " €");
        nykAlaLabel.setText(osake.getToimiala().toString());

        nykBetaLabel.setText(df2.format(osake.getRiski().getBeta()));
        nykVolaLabel.setText(df2.format(osake.getRiski().getVolatiliteetti()));
    }

    private boolean onNumeerinenJaPositiivinen(String str) {
        try {
            double d = Double.parseDouble(str);
            if (d < 0) {
                return false;
            }
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }
    
    private void tietoVaarassaMuodossa() {
        VaaraMuotoGUI huom = new VaaraMuotoGUI();
        huom.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuutaTietojaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuutaTietojaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuutaTietojaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuutaTietojaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuutaTietojaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField betaTextField;
    private javax.swing.JTextField hintaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton muutaButton;
    private javax.swing.JLabel nimiLabel;
    private javax.swing.JTextField nimiTextField;
    private javax.swing.JLabel nykAlaLabel;
    private javax.swing.JLabel nykArvoLabel;
    private javax.swing.JLabel nykBetaLabel;
    private javax.swing.JLabel nykNimiLabel;
    private javax.swing.JLabel nykVolaLabel;
    private javax.swing.JButton paluuButton;
    private javax.swing.JComboBox<String> toimialaComboBox;
    private javax.swing.JTextField volaTextField;
    // End of variables declaration//GEN-END:variables
    private Osake osake;
    private DecimalFormat df2;
    private OsakesalkkuGUI vanhempi;
}
