package liittyma;

import java.text.DecimalFormat;

/**
 *
 * Tämä käyttöliittymäikkuna ilmoittaa käyttäjälle myyntitapahtuman 
 * onnistumisesta ja sen tuotoista/tappioista.
 *
 * @author gexgex
 */
public class MyyntiOnnistuiGUI extends javax.swing.JFrame {

    MyyOsakeGUI vanhempi;

    /**
     * Creates new form myyntiOnnistuiGUI
     */
    public MyyntiOnnistuiGUI() {
        initComponents();
    }

    public MyyntiOnnistuiGUI(MyyOsakeGUI aThis) {
        super("MyyntiOnnistuiGUI");
        this.vanhempi = aThis;
        df2 = new DecimalFormat("0.00");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        osakeLabel = new javax.swing.JLabel();
        tulosLabel = new javax.swing.JLabel();
        reaktioButton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Myynti onnistui");

        osakeLabel.setText("Myit osaketta onnistuneesti!");

        tulosLabel.setText("Jäit voitolle euroa.");

        reaktioButton.setText("Jaaha");
        reaktioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reaktioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tulosLabel)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(osakeLabel)
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(reaktioButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(osakeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tulosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(reaktioButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reaktioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reaktioButtonActionPerformed
        super.dispose();
    }//GEN-LAST:event_reaktioButtonActionPerformed

    /**
     *
     * Metodi asettaa ikkunan tiedot myyntitapahtuman perusteella.
     *
     */
    public void ilmoitus() {
        osakeLabel.setText("Myit osaketta " + vanhempi.getOsake().getNimi() + " onnistuneesti!");

        double tulos = vanhempi.getMyytyOsake().getHinta() - vanhempi.getOsake().getAlkuArvo();
        double arvo = Math.abs(tulos * vanhempi.getMyytyOsake().getMaara());

        if (tulos < 0) {
            tulosLabel.setText("Jäit tappiolle " + df2.format(arvo) + " euroa");
            reaktioButton.setText("Jaaha");
        } else if (tulos > 0) {
            tulosLabel.setText("Jäit voitolle " + df2.format(arvo) + " euroa");
            reaktioButton.setText("Jippii!");
        } else {
            tulosLabel.setText("");
            reaktioButton.setText("Selvä");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyyntiOnnistuiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyyntiOnnistuiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyyntiOnnistuiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyyntiOnnistuiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyyntiOnnistuiGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel osakeLabel;
    private javax.swing.JButton reaktioButton;
    private javax.swing.JLabel tulosLabel;
    // End of variables declaration//GEN-END:variables
    private DecimalFormat df2;
}
