package liittyma;

import java.text.DecimalFormat;
import java.util.HashSet;
import java.util.Set;
import javax.swing.*;
import logiikka.*;

/**
 *
 * Luokka tarjoaa käyttäjälle käyttöliittymän osakesalkun käyttämiseen sekä 
 * eräiden tunnuslukujen tarkasteluun.
 *
 * @author gexgex
 */
public class OsakesalkkuGUI extends javax.swing.JFrame {

    public OsakesalkkuGUI() {
        initComponents();
        salkku = new Salkku();
        laskuri = new Laskuri(salkku);
        listModel = new DefaultListModel();
        osakkeetList.setFixedCellWidth(250);
        df3 = new DecimalFormat("0.000");
        df2 = new DecimalFormat("0.00");
        df1 = new DecimalFormat("0.0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        ostaButton = new javax.swing.JButton();
        myyButton = new javax.swing.JButton();
        paivitaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        osakkeetList = new javax.swing.JList<>();
        osakeLabel = new javax.swing.JLabel();
        arvoLabel = new javax.swing.JLabel();
        maaraLabel = new javax.swing.JLabel();
        toimialaLabel = new javax.swing.JLabel();
        alkuarvoLabel = new javax.swing.JLabel();
        muutosEurLabel = new javax.swing.JLabel();
        muutosPrsLabel = new javax.swing.JLabel();
        betaLabel = new javax.swing.JLabel();
        volaLabel = new javax.swing.JLabel();
        muutosEur = new javax.swing.JLabel();
        muutosPrs = new javax.swing.JLabel();
        beta = new javax.swing.JLabel();
        volatiliteetti = new javax.swing.JLabel();
        alkuarvo = new javax.swing.JLabel();
        toimiala = new javax.swing.JLabel();
        maara = new javax.swing.JLabel();
        arvo = new javax.swing.JLabel();
        nimi = new javax.swing.JLabel();
        lopetaButton = new javax.swing.JButton();
        muutaButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Osakesalkku");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        ostaButton.setText("Osta osaketta");
        ostaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ostaButtonActionPerformed(evt);
            }
        });

        myyButton.setText("Myy osaketta");
        myyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myyButtonActionPerformed(evt);
            }
        });

        paivitaButton.setText("Päivitä");
        paivitaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paivitaButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Osakkeet");

        osakkeetList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                osakkeetListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(osakkeetList);

        osakeLabel.setText("Osake: ");

        arvoLabel.setText("Arvo: ");

        maaraLabel.setText("Määrä:");

        toimialaLabel.setText("Toimiala: ");

        alkuarvoLabel.setText("Alkuarvo: ");

        muutosEurLabel.setText("Muutos (eur): ");

        muutosPrsLabel.setText("Kasvu (%):");

        betaLabel.setText("Beta-arvo: ");

        volaLabel.setText("Volatiliteetti: ");

        muutosEur.setText("-");

        muutosPrs.setText("-");

        beta.setText("-");

        volatiliteetti.setText("-");

        alkuarvo.setText("-");

        toimiala.setText("-");

        maara.setText("-");

        arvo.setText("-");

        nimi.setText("-");

        lopetaButton.setText("Lopeta");
        lopetaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lopetaButtonActionPerformed(evt);
            }
        });

        muutaButton.setText("Muuta valitun osakkeen tietoja");
        muutaButton.setEnabled(false);
        muutaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muutaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ostaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(myyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paivitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(muutosEurLabel)
                            .addComponent(muutosPrsLabel)
                            .addComponent(betaLabel)
                            .addComponent(volaLabel)
                            .addComponent(alkuarvoLabel)
                            .addComponent(toimialaLabel)
                            .addComponent(maaraLabel)
                            .addComponent(arvoLabel)
                            .addComponent(osakeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(volatiliteetti)
                            .addComponent(beta)
                            .addComponent(nimi)
                            .addComponent(arvo)
                            .addComponent(maara)
                            .addComponent(toimiala)
                            .addComponent(alkuarvo)
                            .addComponent(muutosPrs)
                            .addComponent(muutosEur))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(muutaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lopetaButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ostaButton)
                        .addGap(18, 18, 18)
                        .addComponent(myyButton)
                        .addGap(18, 18, 18)
                        .addComponent(paivitaButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(osakeLabel)
                    .addComponent(nimi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arvoLabel)
                    .addComponent(arvo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maaraLabel)
                    .addComponent(maara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toimialaLabel)
                    .addComponent(toimiala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alkuarvoLabel)
                    .addComponent(alkuarvo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muutosEurLabel)
                    .addComponent(muutosEur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muutosPrsLabel)
                    .addComponent(muutosPrs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(betaLabel)
                    .addComponent(beta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volaLabel)
                    .addComponent(volatiliteetti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muutaButton)
                    .addComponent(lopetaButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myyButtonActionPerformed
        // TODO add your handling code here:
        JList osakkeet = osakkeetList;

        MyyOsakeGUI myyOsake = new MyyOsakeGUI(this);
        myyOsake.setVisible(true);
    }//GEN-LAST:event_myyButtonActionPerformed

    private void ostaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ostaButtonActionPerformed
        // TODO add your handling code here:

        OstaOsakeGUI ostaOsake = new OstaOsakeGUI(this);
        ostaOsake.setVisible(true);

    }//GEN-LAST:event_ostaButtonActionPerformed

    private void paivitaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paivitaButtonActionPerformed
        // TODO add your handling code here:
        paivitaSalkku();
    }//GEN-LAST:event_paivitaButtonActionPerformed

    private void osakkeetListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_osakkeetListMouseClicked
        if (salkku.getOsakkeet().isEmpty()) {
            return;
        }

        JList lista = (JList) evt.getSource();
        int index = lista.locationToIndex(evt.getPoint());
        if (index >= 0) {
            Object o = lista.getModel().getElementAt(index);
            String osakkeenNimi = o.toString();
            osake = salkku.osakeNimenPerusteella(osakkeenNimi);
        }

        nimi.setText(osake.getNimi());
        maara.setText(String.valueOf(osake.getMaara()));
        arvo.setText(String.valueOf(df3.format(osake.getHinta())) + " €");
        alkuarvo.setText(String.valueOf(df3.format(osake.getAlkuArvo())) + " €");
        muutosEur.setText(String.valueOf(df2.format(laskuri.osakkeenArvonMuutos(osake))) + " €");
        muutosPrs.setText(String.valueOf(df1.format(laskuri.osakkeenArvonKasvuprosentti(osake))) + " %");
        beta.setText(String.valueOf(df2.format(osake.getRiski().getBeta())));
        volatiliteetti.setText(String.valueOf(df2.format(osake.getRiski().getVolatiliteetti())));
        toimiala.setText(osake.getToimiala().toString());

        muutaButton.setEnabled(true);
    }//GEN-LAST:event_osakkeetListMouseClicked

    private void lopetaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lopetaButtonActionPerformed
        super.dispose();
    }//GEN-LAST:event_lopetaButtonActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        paivitaSalkku();
    }//GEN-LAST:event_formMouseClicked

    private void muutaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muutaButtonActionPerformed
        MuutaTietojaGUI muutaTietoja = new MuutaTietojaGUI(this);
        muutaTietoja.asetaTiedot();
        muutaTietoja.setVisible(true);
    }//GEN-LAST:event_muutaButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OsakesalkkuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OsakesalkkuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OsakesalkkuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OsakesalkkuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OsakesalkkuGUI().setVisible(true);
            }
        });
    }

    public void ostaOsake(Osake osake, Riski riski) {
        osake.setRiski(riski);
        salkku.lisaaOsake(osake);
        paivitaLista();
    }

    public void myyOsake(Osake osake) {
        salkku.vaihdaOsaketta(osake);
        paivitaLista();
    }

    public void paivitaLista() {
        osakkeetList.setModel(listModel);
        listModel.clear();
        for (Osake o : salkku.getOsakkeet()) {
            listModel.addElement(o.getNimi());
        }
        paivitaSalkku();
    }

    private void paivitaSalkku() {
        if (salkku.getOsakkeet().isEmpty()) {
            nimi.setText("-");
            maara.setText("-");
            arvo.setText("-");
            alkuarvo.setText("-");
            muutosEur.setText("-");
            muutosPrs.setText("-");
            beta.setText("-");
            volatiliteetti.setText("-");
            toimiala.setText("-");

        } else {
            salkku.setRiski(new Riski(laskuri.salkunBeta(), laskuri.salkunVolatiliteetti()));

            nimi.setText("Kaikki");
            maara.setText(salkku.getOsakkeet().size() + " yritystä");
            arvo.setText(String.valueOf(df2.format(salkku.arvo())) + " €");
            alkuarvo.setText(String.valueOf(df2.format(salkku.alkuArvo())) + " €");
            muutosEur.setText(String.valueOf(df2.format(laskuri.salkunArvonMuutos())) + " €");
            muutosPrs.setText(String.valueOf(df1.format(laskuri.salkunArvonKasvuprosentti())) + " %");
            beta.setText(String.valueOf(df3.format(salkku.getRiski().getBeta())));
            volatiliteetti.setText(String.valueOf(df3.format(salkku.getRiski().getVolatiliteetti())));
            toimiala.setText(salkku.toimialojenLkm() + " eri toimialaa");
        }
        muutaButton.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alkuarvo;
    private javax.swing.JLabel alkuarvoLabel;
    private javax.swing.JLabel arvo;
    private javax.swing.JLabel arvoLabel;
    private javax.swing.JLabel beta;
    private javax.swing.JLabel betaLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton lopetaButton;
    private javax.swing.JLabel maara;
    private javax.swing.JLabel maaraLabel;
    private javax.swing.JButton muutaButton;
    private javax.swing.JLabel muutosEur;
    private javax.swing.JLabel muutosEurLabel;
    private javax.swing.JLabel muutosPrs;
    private javax.swing.JLabel muutosPrsLabel;
    private javax.swing.JButton myyButton;
    private javax.swing.JLabel nimi;
    private javax.swing.JLabel osakeLabel;
    public javax.swing.JList<String> osakkeetList;
    private javax.swing.JButton ostaButton;
    private javax.swing.JButton paivitaButton;
    private javax.swing.JLabel toimiala;
    private javax.swing.JLabel toimialaLabel;
    private javax.swing.JLabel volaLabel;
    private javax.swing.JLabel volatiliteetti;
    // End of variables declaration//GEN-END:variables
    private static Laskuri laskuri;
    private static Salkku salkku;
    private static Osake osake;
    private DecimalFormat df3;
    private DecimalFormat df2;
    private DecimalFormat df1;
    public DefaultListModel listModel;

    public static Salkku getSalkku() {
        return salkku;
    }

    public static Osake getOsake() {
        return osake;
    }

    public void setOsake(Osake osake) {
        this.osake = osake;
    }
}
