package liittyma;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;
import logiikka.*;

/**
 *
 * Luokka tarjoaa käyttäjälle käyttöliittymän osakkeen ostamiseen.
 * HUOM: Ostamalla valmiiksi omistettu osake, sen arvo ja alkuarvo päivittyy, 
 * mutta esimerkiksi toimialaa ja riskitietoja osakkeen ostaminen ei muuta.
 *
 * @author gexgex
 */
public class OstaOsakeGUI extends javax.swing.JFrame {

    OsakesalkkuGUI vanhempi;

    /**
     * Creates new form OstaOsakettaGUI
     */
    public OstaOsakeGUI() {
        initComponents();
    }

    OstaOsakeGUI(OsakesalkkuGUI aThis) {
        super("OstaOsakettaGUI");
        this.vanhempi = aThis;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Toimialat = new javax.swing.ButtonGroup();
        tallennaButton = new javax.swing.JButton();
        perusteollisuus = new javax.swing.JRadioButton();
        teollisuustuotteet = new javax.swing.JRadioButton();
        kulutustavarat = new javax.swing.JRadioButton();
        terveydenhuolto = new javax.swing.JRadioButton();
        kulutuspalvelut = new javax.swing.JRadioButton();
        tietoliikennepalvelut = new javax.swing.JRadioButton();
        rahoitus = new javax.swing.JRadioButton();
        teknologia = new javax.swing.JRadioButton();
        energia = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nimi = new javax.swing.JTextField();
        hinta = new javax.swing.JTextField();
        maara = new javax.swing.JTextField();
        beta = new javax.swing.JTextField();
        volatiliteetti = new javax.swing.JTextField();
        paluuButton = new javax.swing.JButton();
        tyhjennaJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Osta osaketta");

        tallennaButton.setText("Osta osake");
        tallennaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tallennaButtonActionPerformed(evt);
            }
        });

        Toimialat.add(perusteollisuus);
        perusteollisuus.setText("Perusteollisuus");
        perusteollisuus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perusteollisuusActionPerformed(evt);
            }
        });

        Toimialat.add(teollisuustuotteet);
        teollisuustuotteet.setText("Teollisuustuotteet");

        Toimialat.add(kulutustavarat);
        kulutustavarat.setText("Kulutustavarat");

        Toimialat.add(terveydenhuolto);
        terveydenhuolto.setText("Terveydenhuolto");

        Toimialat.add(kulutuspalvelut);
        kulutuspalvelut.setText("Kulutuspalvelut");

        Toimialat.add(tietoliikennepalvelut);
        tietoliikennepalvelut.setText("Tietoliikennepalvelut");

        Toimialat.add(rahoitus);
        rahoitus.setText("Rahoitus");

        Toimialat.add(teknologia);
        teknologia.setText("Teknologia");

        Toimialat.add(energia);
        energia.setText("Energia");

        jLabel1.setText("Nimi");

        jLabel2.setText("Hinta");

        jLabel3.setText("Määrä");

        jLabel4.setText("Beta");

        jLabel5.setText("Volatiliteetti");

        jLabel6.setFont(new java.awt.Font("Ubuntu Medium", 1, 15)); // NOI18N
        jLabel6.setText("Täytä joka kohta!");

        nimi.setText("Nordea");
        nimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimiActionPerformed(evt);
            }
        });

        hinta.setText("9");
        hinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintaActionPerformed(evt);
            }
        });

        maara.setText("1000");

        beta.setText("0.7");

        volatiliteetti.setText("0.23");
        volatiliteetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volatiliteettiActionPerformed(evt);
            }
        });

        paluuButton.setText("Paluu");
        paluuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paluuButtonActionPerformed(evt);
            }
        });

        tyhjennaJButton.setText("Tyhjennä");
        tyhjennaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyhjennaJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tyhjennaJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addComponent(volatiliteetti)
                            .addComponent(beta)
                            .addComponent(maara)
                            .addComponent(hinta)
                            .addComponent(nimi))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tietoliikennepalvelut)
                    .addComponent(perusteollisuus)
                    .addComponent(teollisuustuotteet)
                    .addComponent(kulutustavarat)
                    .addComponent(terveydenhuolto)
                    .addComponent(kulutuspalvelut)
                    .addComponent(rahoitus)
                    .addComponent(teknologia)
                    .addComponent(energia)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paluuButton)
                        .addGap(22, 22, 22)
                        .addComponent(tallennaButton)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(perusteollisuus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(teollisuustuotteet, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kulutustavarat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(terveydenhuolto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kulutuspalvelut, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tietoliikennepalvelut))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(maara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(beta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rahoitus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teknologia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(energia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(volatiliteetti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tallennaButton)
                    .addComponent(paluuButton)
                    .addComponent(tyhjennaJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perusteollisuusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perusteollisuusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perusteollisuusActionPerformed

    private void tallennaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tallennaButtonActionPerformed
        if (nimi.getText().isEmpty() || hinta.getText().isEmpty() || maara.getText().isEmpty() || beta.getText().isEmpty() || volatiliteetti.getText().isEmpty()) {
            tietoPuuttuu();
            return;
        }

        if (!onNumeerinenJaPositiivinen(hinta.getText()) || !onPositiivinenKokonaisluku(maara.getText()) || !onNumeerinenJaPositiivinen(beta.getText()) || !onNumeerinenJaPositiivinen(volatiliteetti.getText())) {
            tietoVaarassaMuodossa();
            return;
        }

        String nimi = this.nimi.getText();
        String hintaTxt = this.hinta.getText();
        double hinta = Double.parseDouble(hintaTxt);
        String maaraTxt = this.maara.getText();
        int maara = Integer.parseInt(maaraTxt);

        String betaTxt = this.beta.getText();
        double beta = Double.parseDouble(betaTxt);
        String volaTxt = this.volatiliteetti.getText();
        double volatiliteetti = Double.parseDouble(volaTxt);
        Osake osake = new Osake(nimi, hinta, maara);
        Riski riski = new Riski(beta, volatiliteetti);
        Toimiala toimiala = valittuToimiala();

        if (toimiala == null) {
            tietoPuuttuu();
            return;
        }

        osake.setToimiala(toimiala);
        vanhempi.ostaOsake(osake, riski);

        super.dispose();
    }//GEN-LAST:event_tallennaButtonActionPerformed

    private Toimiala valittuToimiala() {
        Enumeration<AbstractButton> nappulat = Toimialat.getElements();
        JRadioButton valittuNappi = null;

        while (nappulat.hasMoreElements()) {
            valittuNappi = (JRadioButton) nappulat.nextElement();
            if (valittuNappi.isSelected()) {
                break;
            }
            if (!nappulat.hasMoreElements()) {

                return null; //tästä myös virheilmoitus!!
            }
        }
        String toimialanNimi = valittuNappi.getText().toUpperCase();
        Toimiala toimiala = Toimiala.merkkijonoToimialaksi(toimialanNimi);

        return toimiala;
    }

    private void nimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimiActionPerformed

    private void volatiliteettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volatiliteettiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volatiliteettiActionPerformed

    private void hintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hintaActionPerformed

    private void paluuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paluuButtonActionPerformed
        super.dispose();
    }//GEN-LAST:event_paluuButtonActionPerformed

    private void tyhjennaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyhjennaJButtonActionPerformed
        nimi.setText("");
        hinta.setText("");
        maara.setText("");
        beta.setText("");
        volatiliteetti.setText("");
    }//GEN-LAST:event_tyhjennaJButtonActionPerformed

    private void tietoPuuttuu() {
        TietoPuuttuuGUI huom = new TietoPuuttuuGUI();
        huom.setVisible(true);
    }

    private void tietoVaarassaMuodossa() {
        VaaraMuotoGUI huom = new VaaraMuotoGUI();
        huom.setVisible(true);
    }

    private boolean onNumeerinenJaPositiivinen(String str) {
        try {
            double d = Double.parseDouble(str);
            if (d < 0) {
                return false;
            }
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }
    
    private boolean onPositiivinenKokonaisluku(String str) {
        try {
            int d = Integer.parseInt(str);
            if (d < 0) {
                return false;
            }
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OstaOsakeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OstaOsakeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OstaOsakeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OstaOsakeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OstaOsakeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Toimialat;
    private javax.swing.JTextField beta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton energia;
    public javax.swing.JTextField hinta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton kulutuspalvelut;
    private javax.swing.JRadioButton kulutustavarat;
    private javax.swing.JTextField maara;
    public javax.swing.JTextField nimi;
    private javax.swing.JButton paluuButton;
    private javax.swing.JRadioButton perusteollisuus;
    private javax.swing.JRadioButton rahoitus;
    public javax.swing.JButton tallennaButton;
    private javax.swing.JRadioButton teknologia;
    private javax.swing.JRadioButton teollisuustuotteet;
    private javax.swing.JRadioButton terveydenhuolto;
    private javax.swing.JRadioButton tietoliikennepalvelut;
    private javax.swing.JButton tyhjennaJButton;
    private javax.swing.JTextField volatiliteetti;
    // End of variables declaration//GEN-END:variables
}
